[package]
edition = "2021"
name = "zoned"
version = "0.1.0"

[[bin]]
name = "zoned"
path = "main.rs"

[profile.release]
incremental = true
lto = true
opt-level = 3

[profile.dev]
incremental = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[dependencies]
anyhow = { version = "1.0.79", features = [ "backtrace" ] }
clap = { version = "4", default-features = false, features = [
    "derive",
    "help",
    "std",
    "usage",
] }
clap-verbosity-flag = "2.1.2"
cloudflare = { version = "0.11.0", default-features = false, features = [
    "rustls-tls",
] }
config = { version = "0.13.4", default-features = false, features = [ "toml" ] }
local-ip-address = "0.5.6"
reqwest = { version = "0.11.23", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = "1.0.195"
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = [
    "macros",
    "net",
    "rt-multi-thread"
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
xdg = "2.5.2"
