[package]
edition = "2021"
name = "zoned"
version = "0.0.2"

[[bin]]
name = "zoned"
path = "main.rs"

[dependencies]
anyhow = { version = "1.0.72", features = [ "backtrace" ] }
cloudflare = { git = "https://github.com/cloudflare/cloudflare-rs", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
config = { version = "0.13.3", default-features = false, features = ["toml"] }
default-net = "0.16.2"
ip_network = "0"
regex = "1.9"
reqwest = { version = "0.11.18", default-features = false, features = [
    "blocking",
    "json",
    "rustls-tls",
] }
serde = "1.0.171"
serde_json = "1.0.103"
xdg = "2.5.0"

