[build]
build-std = false # do not build the std library.
default-target = "aarch64-unknown-linux-gnu"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH",
]
xargo = false
