[Config]
domain = "pants.electricrain.com"

[LAN]
shared-network-name = "net_LAN_eth1_10.0.0.0-24"
subnet = "10.0.0.0/24"

    [LAN.clients]
    # 10.0.0.1/28
    "10.0.0.1" = { mac = "78:8a:20:7e:cd:a0", name = "gateway", ipv6 = "2600:1700:9580:2551::1" }
    "10.0.0.3" = { mac = "18:e8:29:2c:fd:11", name = "unifi-switch-48-pro" }

    # 10.0.0.16/28
    "10.0.0.15" = { mac = "18:e8:29:43:21:fb", name = "wap-backyard" }
    "10.0.0.16" = { mac = "f0:9f:c2:61:d3:55", name = "wap-downstairs" }
    "10.0.0.17" = { mac = "f0:9f:c2:61:d0:e1", name = "wap-garage" }
    "10.0.0.18" = { mac = "f0:9f:c2:61:d2:45", name = "wap-upstairs" }
    "10.0.0.20" = { mac = "b4:fb:e4:70:63:2c", name = "wap-fans" }
    "10.0.0.21" = { mac = "74:83:c2:76:73:59", name = "wap-master-bedroom" }

    # 10.0.0.32/28
    "10.0.0.32" = { mac = "44:d9:e7:94:ce:9d", name = "uvc-garage-back" }
    "10.0.0.33" = { mac = "44:d9:e7:94:ce:56", name = "uvc-garage-front" }
    "10.0.0.34" = { mac = "f0:9f:c2:13:93:79", name = "uvc-north-east" }
    "10.0.0.35" = { mac = "b4:fb:e4:e0:0c:67", name = "uvc-north-east-upstairs" }
    "10.0.0.36" = { mac = "b4:fb:e4:e0:0b:bb", name = "uvc-north-west" }
    "10.0.0.37" = { mac = "b4:fb:e4:fe:e8:1e", name = "uvc-south-east" }
    "10.0.0.38" = { mac = "b4:fb:e4:e0:0c:10", name = "uvc-south-west" }

    "10.0.0.39" = { mac = "44:d9:e7:94:9a:d3", name = "uvc-backyard", skip = true }
    "10.0.0.40" = { mac = "fc:ec:da:8f:c2:29", name = "uvc-g3-pro-unused-1", skip = true }
    "10.0.0.41" = { mac = "44:d9:e7:94:9a:f0", name = "uvc-g3-unused-1", skip = true }
    "10.0.0.42" = { mac = "80:2a:a8:cc:8f:aa", name = "uvc-g3-unused-2", skip = true }

    # 10.0.0.96/28
    "10.0.0.100" = { mac = "ac:1f:6b:41:29:b0", name = "server", ipv6 = "2600:1700:9580:2551:ae1f:6bff:fe41:29b0", aliases = ["crashplan", "dl", "pl", "nvr", "plex", "unifi", "windows"] }
    "10.0.0.101" = { mac = "ac:1f:6b:4b:87:91", name = "server-ipmi", ipv6 = "2600:1700:9580:2551:ae1f:6bff:fe4b:8791", aliases = ["ipmi"] }
    "10.0.0.102" = { mac = "ac:1f:6b:41:29:b1", name = "server-eth2", ipv6 = "2600:1700:9580:2551:ae1f:6bff:fe41:29b1" }
    "10.0.0.103" = { mac = "30:05:5c:70:8d:22", name = "printer-ethernet", aliases = ["printer"], ipv6 = "2600:1700:9580:2551:3205:5cff:fe70:8d22" }
    "10.0.0.104" = { mac = "00:0c:29:0d:3f:4e", name = "windows-vm" }
    "10.0.0.105" = { mac = "98:10:e8:f1:40:c1", name = "imac", ipv6 = "2600:1700:9580:2551:10a6:7899:7e8c:46ff" }

    # 10.0.0.112/28 - Personal Devices
    "10.0.0.112" = { mac = "68:fe:f7:2d:2e:62", name = "apple-watch-dan" }
    "10.0.0.113" = { mac = "f8:6f:c1:51:4a:cb", name = "apple-watch-karine" }
    "10.0.0.114" = { mac = "f0:99:b6:01:6f:30", name = "iphone-dan" }
    "10.0.0.115" = { mac = "34:42:62:08:34:d5", name = "ipad-dan" }
    "10.0.0.116" = { mac = "34:42:62:5e:f1:e6", name = "ipad-karine" }
    "10.0.0.117" = { mac = "f0:99:b6:08:df:ee", name = "iphone-karine" }
    "10.0.0.118" = { mac = "78:7b:8a:47:43:ed", name = "ipad-olivia", ipv6 = "2600:1700:9580:2551:1cf5:da6e:5c22:331b" }
    "10.0.0.119" = { mac = "78:7b:8a:4a:b3:7e", name = "ipad-eliza", ipv6 = "2600:1700:9580:2551:eb:eeef:9ac4:76c8" }
    "10.0.0.120" = { mac = "8c:85:90:5e:e8:fb", name = "dsully-mn2", ipv6 = "2600:1700:9580:2551:1c17:c93d:6580:64b3" }
    "10.0.0.121" = { mac = "00:e1:38:00:00:5b", name = "dsully-mn2-eth" }
    "10.0.0.122" = { mac = "38:f9:d3:de:0a:a6", name = "oyster" }
    "10.0.0.123" = { mac = "50:f5:da:a9:38:e5", name = "kindle-dan" }
    "10.0.0.124" = { mac = "ac:63:be:87:70:29", name = "kindle-karine" }
    "10.0.0.125" = { mac = "00:08:22:07:12:52", name = "karoo" }
    "10.0.0.126" = { mac = "10:c6:fc:8b:55:12", name = "garmin-edge" }

    # 10.0.0.128/28 - House Infrastructure
    "10.0.0.128" = { mac = "1c:ca:e3:77:d1:c0", name = "doorbird" }
    "10.0.0.129" = { mac = "44:61:32:84:4e:f7", name = "ecobee3-downstairs" }
    "10.0.0.130" = { mac = "44:61:32:9c:a0:5d", name = "ecobee3-upstairs" }
    "10.0.0.131" = { mac = "00:23:38:11:6c:00", name = "floor-heat-kids" }
    "10.0.0.132" = { mac = "00:23:38:11:72:16", name = "floor-heat-master" }
    "10.0.0.133" = { mac = "60:64:05:63:e9:9e", name = "lutron-bridge" }
    "10.0.0.134" = { mac = "00:0f:e7:07:69:51", name = "radiora2-controller-a" }
    "10.0.0.135" = { mac = "00:0f:e7:04:06:c3", name = "radiora2-controller-b" }
    "10.0.0.136" = { mac = "64:52:99:a7:22:84", name = "liftmaster-bridge" }
    "10.0.0.137" = { mac = "00:17:88:20:58:ab", name = "hue-light-bridge" }

    "10.0.0.138" = { mac = "18:b4:30:2d:f9:ed", name = "nest-protect-back-bedroom" }
    "10.0.0.139" = { mac = "18:b4:30:2e:0f:e2", name = "nest-protect-entry" }
    "10.0.0.140" = { mac = "18:b4:30:33:9e:64", name = "nest-protect-front-bedroom" }
    "10.0.0.141" = { mac = "18:b4:30:2e:01:69", name = "nest-protect-hallway" }
    "10.0.0.142" = { mac = "18:b4:30:33:9c:6f", name = "nest-protect-master-bedroom" }
    "10.0.0.143" = { mac = "18:b4:30:2d:f6:b4", name = "nest-protect-upstairs" }

    # 10.0.0.144/28 - Media
    "10.0.0.144" = { mac = "44:c3:06:43:a7:92", name = "bluesound-office" }
    "10.0.0.145" = { mac = "00:05:cd:84:83:01", name = "denon", aliases = ["avr"] }
    "10.0.0.146" = { mac = "5c:f3:70:3c:5e:98", name = "neeo" }
    "10.0.0.147" = { mac = "60:64:05:a5:da:37", name = "neeo-remote" }
    "10.0.0.148" = { mac = "1a:2b:3c:4d:8e:ba", name = "nintendo-switch-ethernet" }
    "10.0.0.149" = { mac = "04:03:d6:73:c0:fa", name = "nintendo-switch-wifi" }
    "10.0.0.150" = { mac = "f8:46:1c:5f:8a:b3", name = "playstation4" }
    "10.0.0.151" = { mac = "00:04:4b:5c:47:e0", name = "shield" }
    "10.0.0.152" = { mac = "a4:8d:3b:fb:f2:65", name = "vizio-tv-ethernet" }
    "10.0.0.153" = { mac = "a4:8d:3b:20:55:b0", name = "vizio-tv-wifi" }
    "10.0.0.154" = { mac = "b8:e9:37:a9:01:48", name = "sonos-deck" }
    "10.0.0.155" = { mac = "b8:e9:37:a9:5b:a2", name = "sonos-dining-room" }
    "10.0.0.156" = { mac = "b8:e9:37:a8:88:c0", name = "sonos-front-bedroom" }
    "10.0.0.157" = { mac = "b8:e9:37:a9:01:f6", name = "sonos-kids-bedroom" }
    "10.0.0.158" = { mac = "b8:e9:37:a8:fc:38", name = "sonos-master-bedroom" }

    # 10.0.0.160/28 - Cars
    "10.0.0.160" = { mac = "04:4e:af:bb:a7:31", name = "tesla-model-3" }
    "10.0.0.161" = { mac = "a0:14:3d:f3:9d:c4", name = "tesla-model-s" }
    "10.0.0.162" = { mac = "4c:55:cc:12:97:ae", name = "juicebox-outside" }
    "10.0.0.163" = { mac = "4c:55:cc:12:92:75", name = "juicebox-garage" }

    # 10.0.0.176/28 - Power Control
    "10.0.0.176" = { mac = "0c:c7:31:47:9c:47", name = "currant-outlet-1" }
    "10.0.0.177" = { mac = "50:c7:bf:31:40:38", name = "kasa-outlet-living" }
    "10.0.0.178" = { mac = "50:c7:bf:30:4a:f6", name = "kasa-outlet-office" }
    "10.0.0.179" = { mac = "00:7e:56:91:75:2f", name = "powerstrip-rack" }
    "10.0.0.180" = { mac = "e4:23:54:0d:43:e9", name = "outlet-kids-bedroom" }
    "10.0.0.181" = { mac = "b0:be:76:2a:dc:fa", name = "powerstrip-living" }
    "10.0.0.182" = { mac = "e4:23:54:0d:4a:71", name = "exterior-lighting-outlet" }

    # 10.0.0.192/28
    "10.0.0.192" = { mac = "04:52:f3:01:1b:90", name = "ipad-back-bedroom" }
    "10.0.0.193" = { mac = "34:12:98:c2:15:01", name = "ipad-front-bedroom" }
    "10.0.0.194" = { mac = "34:12:98:a2:30:99", name = "ipad-living-room" }
    "10.0.0.195" = { mac = "34:12:98:ab:8f:55", name = "ipad-master-bedroom" }
    "10.0.0.196" = { mac = "40:cb:c0:ab:5c:4c", name = "appletv", ipv6 = "2600:1700:9580:2551:18bf:d6bf:1e79:5b7f" }

    # 10.0.0.208/28 - Random IoT
    "10.0.0.208" = { mac = "00:80:92:57:00:8c", name = "scansnap" }
    "10.0.0.209" = { mac = "b8:27:eb:fd:e0:fd", name = "sisyphus" }
    "10.0.0.210" = { mac = "60:01:94:19:92:15", name = "tittle-light" }
    "10.0.0.211" = { mac = "00:18:61:27:09:45", name = "ooma" }
    "10.0.0.212" = { mac = "ac:04:0b:0b:f1:f2", name = "peloton-ethernet" }
    "10.0.0.213" = { mac = "ac:04:0b:01:47:47", name = "peloton-wifi" }
    "10.0.0.214" = { mac = "80:a5:89:db:6e:aa", name = "rachio-iro" }
    "10.0.0.215" = { mac = "00:1d:c0:64:62:fb", name = "solar-bridge" }
    "10.0.0.216" = { mac = "78:29:ed:c8:d9:f5", name = "tmobile-cell-spot" }
    "10.0.0.217" = { mac = "ac:cf:23:75:16:40", name = "anova" }
    "10.0.0.218" = { mac = "d8:61:62:9d:bc:78", name = "august-connect" }
    "10.0.0.219" = { mac = "00:24:e4:35:51:70", name = "withings-scale" }
    "10.0.0.220" = { mac = "00:0e:c6:21:00:3c", name = "hottub" }

    # 10.0.0.224/28 - Remote VPN
    "10.0.0.224" = { name = "server-vpn" }
    "10.0.0.225" = { name = "dsully-mn2-vpn" }

    # 10.0.0.240/28 - DHCP

[Fans]
shared-network-name = "net_Fans_eth1_10.0.20.0-24"
subnet = "10.0.20.0/24"
vlan = 20

    [Fans.clients]
    "10.0.20.2" = { mac = "20:f8:5e:ab:35:9d", name = "fan-back-bedroom" }
    "10.0.20.3" = { mac = "20:f8:5e:d2:64:84", name = "fan-back-bedroom-controller" }
    "10.0.20.4" = { mac = "20:f8:5e:aa:6c:8f", name = "fan-front-bedroom" }
    "10.0.20.5" = { mac = "20:f8:5e:d2:74:38", name = "fan-front-bedroom-controller" }
    "10.0.20.6" = { mac = "20:f8:5e:aa:7c:f8", name = "fan-living-room" }
    "10.0.20.7" = { mac = "20:f8:5e:d2:4d:17", name = "fan-living-room-controller" }
    "10.0.20.8" = { mac = "20:f8:5e:ab:32:56", name = "fan-master-bedroom" }
    "10.0.20.9" = { mac = "20:f8:5e:d2:7e:d6", name = "fan-master-bedroom-controller" }
