[tool.poetry]
name = "zoned"
version = "0.1.0"
description = "A tool to generate Unifi Controller configuration."
authors = ["Dan Sully <dsully@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
natsort = "^6.0"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
mypy = "^0.701.0"
flake8 = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
