---
name: Publish

on:
  workflow_dispatch:

jobs:
  homebrew:
    name: Publish to dsully/homebrew-tap
    runs-on: ubuntu-latest
    steps:
      - name: Release my project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: dsully
          homebrew_tap: homebrew-tap
          formula_folder: Formula

          commit_owner: Dan Sully
          commit_email: dan+github@sully.org

          github_token: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}

          install: |
            bin.install "cloudflare-dns-updater"

          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: true

          update_readme_table: true

          debug: true
